version: '1.0'
services:

  user_notification_consumer:
    build: ./backend
    container_name: user_notification_consumer
    command: [ "npm", "run","devConsumerUser"]

  asset_notification_consumer:
    build: ./backend
    container_name: asset_notification_consumer
    command: [ "npm", "run", "devConsumerAsset" ]

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgAssetManagement: