version: '1.0'
services:
  frontend:
    build: ./frontend
    container_name: client_frontend
    ports:
      - 5173:5173
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: api_backend
    ports:
      - 5001:5001
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asset-management
    ports:
      - 9000:5432
    volumes:
      - pgAssetManagement:/var/lib/postgresql/data
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgAssetManagement: